- name: "Create user config file directories, if not exist"
  ansible.builtin.file:
    path: "{{ kitty_config_file_path | dirname }}"
    state: directory
    owner: "{{ kitty_user_name }}"
    mode: '755'
  become: true
  become_user: root

- name: "Configure all kitty behavior in '{{ kitty_config_file_path }}'"
  ansible.builtin.template:
    dest: "{{ kitty_config_file_path }}"
    src: "kitty.j2"
    owner: "{{ kitty_user_name }}"
    mode: '644'
    force: yes
  become: true
  become_user: root

